<tr>
  <td>
    <a href="<?= $this->url('todos/default', ['id' => $todo->getId()]) ?>"><?=$todo->getCliente() ?></a>
  </td>
  <td><?=$todo->getLavoro()?></td>
  <td><?=date_format($todo->getDataconsegna(), 'd-m-Y')?></td>
  <td><?=date_format ($todo->getOraconsegna(), 'h:m')?></td>
  <td>
  <!--<button hidden><span class="glyphicon glyphicon-pencil"></span> -->
  <button><span class="glyphicon glyphicon-pencil"></span> 
  </button>
  <button><span class="glyphicon  glyphicon-remove"></span>
  </button>
</td>
</tr>
