<tr>
  <td>
    <a href="<?= $this->url('todos/default', ['cliente' => $todo->getCliente()]) ?>"><?=$todo->getCliente() ?></a>
  </td>
  <td><?=$todo->getLavoro()?></td>
  <td><?=date_format($todo->getDataconsegna(), 'd-m-Y')?></td>
  <td><?=$todo->getPriorita()?></td>
</tr>


        <tr>
            <th scope="row">
              <a href="<?= $this->url('todos/default', ['cliente' => $todo->getCliente()]) ?>"><?=$todo->getCliente() ?></a>
            </th>
            <td><?=$todo->getLavoro()?></td>
            <td><?=date_format($todo->getDataconsegna(), 'd-m-Y')?></td>

        </tr>
