<div id="listMain" class="col-xs-12"> <!-- Start List Main -->
			<div class="row">
				<div class="col-xs-12">
                    <table>
                        <thead>
                            <tr>
                                <th>Cliente</th>
                                <th>Lavoro</th>
                                <th>Consegna</th>
                                <th>Priorità</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td> </td>
                                <td> </td>
                                <td> </td>
                                <td> </td>
                                <td>
                                    <button ><span class="glyphicon glyphicon-pencil"></span>
                                    </button>
                                    <button><span class="glyphicon  glyphicon-remove"></span>
                                    </button></td>
                            </tr>
                        </tbody>
                    </table>
                    <hr>
				</div>
            </div>
		</div> <!-- End List Main -->

		<div class="tasti">
			<div class="row">
                <div class="col-xs-2">
					  <button type="button" class="btn">Lista completa</button>
				</div>
                <div class="col-xs-2">
					  <button type="button" class="btn btn-success">Nuovo Lavoro</button>
                </div>
            </div>
         </div>
