<div class="row">
        <div class="col-xs-11">
            <div class="pull-right">
            <form class="form-inline">
                <div class="form-group">
                    <label class="sr-only" for="exampleInputEmail3">Email address</label>
                    <input type="email" class="form-control  input-sm" id="exampleInputEmail3" placeholder="Email">
                </div>
                <div class="form-group">
                    <label class="sr-only" for="exampleInputPassword3">Password</label>
                    <input type="password" class="form-control input-sm" id="exampleInputPassword3" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-default btn-xs">Sign in</button>
            </form>
            </div>
        </div>
    </div>



<div id="listMain" class="col-xs-12"> <!-- Start List Main -->
			<div class="row">
				<div class="col-xs-12">
                    <table>
                        <thead>
                            <tr>
                                <th>Cliente</th>
                                <th>Lavoro</th>
                                <th>Data consegna</th>
                                <th>Ora consegna</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                              <?php foreach($this->listaTodos as $todo) {
                                echo $this->partial('partials/todo.phtml', ['todo' => $todo]);
                              }?>
                        </tbody>
                    </table>
                    <hr>
				</div>
            </div>
		</div>
