      <?php
        foreach($this->lista as $todo) {
            echo $this->partial('partials/todoList.phtml', ['todo' => $todo]);
        } ?>

                <div class="tasti">
        			<div class="row">
                        <div class="col-xs-2 pull-right">
                               <button alt="Nuovo"><span class="glyphicon glyphicon-list-alt"></span></button>
                            <button alt="OK, ritorna"><span class="glyphicon glyphicon-thumbs-up"></span></button>
        				</div>
                    </div>
                    <hr>
                 </div>
