<h2>Modifica ToDo</h2>

<?php
$this->form->prepare();
echo $this->form()->openTag($form);
?>

    <?php foreach($this->form->getElements() as $element) { ?>
    <div class="form-group">
        <?php


            echo $this->formLabel($element);
            echo $this->formElement($element);
            echo $this->formElementErrors($element);



         ?>
    </div>
    <?php } ?>

    <!-- Button -->
    <div class="form-group">
      <label class="col-md-4 control-label"></label>
      <div class="col-md-4">
        <button type="submit" class="btn btn-warning" >SALVA <span class="glyphicon glyphicon-send"></span></button>
      </div>
    </div>

<?=$this->form()->closeTag($form);?>
