<div id="listMain" class="col-xs-12"> <!-- Start List Main -->

	<?php
	$this->form->prepare();

	// Get the form label plugin
	$formLabel = $this->plugin('formLabel');

	echo $this->form()->openTag($form);
	?>

			<div class="row">
				<div class="col-xs-12">
                    <table>
                        <thead>
                            <tr>
                                <th class="schedalav">Cliente</th>
                                <th class="schedalav">Lavoro</th>
                                <th class="schedalav">Data di Arrivo</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
																	 <?php
																      $cliente = $form->get('cliente');
																      echo $formLabel->openTag();
																			echo $this->formInput($cliente) . $this->formElementErrors($cliente) . $formLabel->closeTag(); ?>
																</td>
                                <td>
																	<td>
																		 <?php
																				$lavoro = $form->get('lavoro');
																				echo $formLabel->openTag();
																				echo $this->formInput($lavoro) . $this->formElementErrors($lavoro) . $formLabel->closeTag(); ?>
																</td>
                                <td>
																	<?php
																		 $datacreazione = $form->get('datacreazione');
																		 echo $formLabel->openTag();
																		 echo $this->formInput($datacreazione) . $this->formElementErrors($datacreazione) . $formLabel->closeTag(); ?>
																</td>
                            </tr>

                             <thead>
                            <tr>
                                <th class="schedalav">E-Mail</th>
                                <th class="schedalav">Telefono</th>
                                <th class="schedalav">Consegna</th>
</tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
																	<?php
																		 $mail = $form->get('mail');
																		 echo $formLabel->openTag();
																		 echo $this->formInput($mail) . $this->formElementErrors($mail) . $formLabel->closeTag(); ?>
                                <td>
																	<?php
																		 $telefono = $form->get('telefono');
																		 echo $formLabel->openTag();
																		 echo $this->formInput($telefono) . $this->formElementErrors($telefono) . $formLabel->closeTag(); ?>
                                <td>
																	<?php
																		 $oraconsegna = $form->get('oraconsegna');
																		 echo $formLabel->openTag();
																		 echo $this->formInput($oraconsegna) . $this->formElementErrors($oraconsegna) . $formLabel->closeTag(); ?>
                            </tr>
                        </tbody>
                             <thead>
                            <tr>
                                <th class="schedalav">Referente</th>
                                <th colspan="2" class="schedalav">Note</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
																	<?php
																		 $referente = $form->get('referente');
																		 echo $formLabel->openTag();
																		 echo $this->formInput($referente) . $this->formElementErrors($referente) . $formLabel->closeTag(); ?>
																	 </td>
                                <td colspan="2">
																	<?php
																		 $note = $form->get('note');
																		 echo $formLabel->openTag();
																		 echo $this->formInput($note) . $this->formElementErrors($note) . $formLabel->closeTag(); ?>
																	 </td>
                            </tr>
                    </table>
				</div>
            </div>
		</div>

		<div class="tasti">
			<div class="row">
                <div class="col-xs-3">
					  <button alt="Modifica" ><span class="glyphicon glyphicon-edit" href="<?=$this->url('todos/modifica', ['id' => $todo->getId()])?>" ></span></button>
                      <button alt="Elimina"><span class="glyphicon glyphicon-remove" href="<?=$this->url('todos/elimina', ['id' => $todo->getId()])?>"> </span></button>
				</div>
            </div>
                     <hr class="divisor">
         </div>
            <!-- End List Main -->
