<?php echo $this->doctype(); ?>

<html lang="it">

    <head>
        <?php echo $this->headTitle('ToDoList')->setSeparator(' - ')->setAutoEscape(false) ?>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- styles -->
        <?php echo $this->headLink()->prependStylesheet($this->basePath('css/normalize.css'))
                                     ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                                     ->appendStylesheet($this->basePath('css/style.css'))
                                     ?>

    </head>
    <body>
        <?=$this->partial('partials/header.phtml'); ?>
        <main>
            <?php echo $this->content; ?>
        </main>
    </body>
    <!-- scripts -->
    <?php echo $this->inlineScript()->prependFile($this->basePath('/js/bootstrap.min.js'))
                                    ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js') ?>

</html>
