

	<div class="container">
        <!--start container-->
		<div class="row">
			<div class="col-xs-12">
				<hr>
                <img src="img/LaTipografica_logo.png" alt="LTP" class="text-center">
				<h1 class="text-center">TO DO LIST</h1>
                <hr>
			</div>
		</div>
		<div id="listMain"> <!-- Start List Main -->
			<div class="row">
				<div class="col-xs-12">
                    <table>
                        <thead>
                            <tr>
                                <th>Cliente</th>
                                <th>Lavoro</th>
                                <th>Consegna</th>
                                <th>Priorità</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                              <?php foreach($this->listaTodos as $todo) {
                                echo $this->partial('partials/todo.phtml', ['todo' => $todo]);
                              } ?>

                            </tr>
                        </tbody>
                    </table>
				</div>
            </div>
		</div> <!-- End List Main -->
    <hr>
		<div class="tasti">
			<div class="row">
			 <div class="col-xs-12">
					  <button type="button" class="btn btn-success">Nuovo Lavoro</button>
				</div>
			</div>
         </div>
     <hr>
    </div>
					<!--end container-->
